services:
    car_loan_nginx:
        image: nginx:1.17.9-alpine
        container_name: car_loan_nginx
        volumes:
            - ./:/var/www
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/config.template:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - car_loan_php
        environment:
            NGINX_HOST: ${BASE_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    car_loan_php:
        build:
            context: docker/php
        container_name: car_loan_php
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

    car_loan_mysql:
        image: mysql:8.0
        container_name: car_loan_mysql
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
            - ./docker/logs/mysql:/var/log/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
